apiVersion: v1
kind: ConfigMap
metadata:
  name: jobvacancyconfig 
data:
  RACK_ENV: "production"
  PORT: "3000"
  DATABASE_URL: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWOR)D@postgres-svc:5432/$(POSTGRES_DB)
