apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobvacancy
  labels:
    app: jobvacancy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobvacancy
  template:
    metadata:
      labels:
        app: jobvacancy
    spec:
      containers:
      - name: webapp
        image: nicopaez/jobvacancy-ruby:1.0.5
        envFrom:
          - secretRef:
              name: secret-postgres
          - configMapRef:
              name: jobvacancyconfig
        env: 
          - name: DATABASE_URL
            value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-svc:5432/$(POSTGRES_DB)
