apiVersion: apps/v1
kind: Deployment
metadata:
  name: passwordapi
  labels:
    app: passwordapi
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: passwordapi
  template:
    metadata:
      labels:
        app: passwordapi
    spec:
      containers:
      - name: passwordapi
        image: nicopaez/password-api:1.5.0-java 
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            host: localhost
            path: /actuator/health
            port: 8080
