version: '3'
services:
  pswd1:
    image: nicopaez/password-api
    ports:
    - "3001:3000"
    expose:
    - "3000"

  pswd2:
    image: nicopaez/password-api
    ports:
    - "3002:3000"
    expose:
    - "3000"
  nginx:
    image: nginx
    volumes: 
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8080:80"
    depends_on:
    - pswd1
    - pswd2
    links:
    - pswd1
    - pswd2
